### ISSUE TITLE
Broken in Gnome 3.30

### ISSUE THREAD

**Issue by ProfRon** [tpyl/gssnaptoneighbors#4]
Gnome 3.30 seems to have broken this great extension. At least for me, under Arch Linux, using the version from extensions.gnome.org.  It no longer seems to do anything at all (at least it doesn't do anything BAD).

**Comment by ProfRon** [comment]
P.S. Also broken in the version from github, i.e. "git clone https://github.com/tpyl/gssnaptoneighbors.git", symbolic link, log out and back in for good measure.... Doesn't make much difference.  :-(

**Comment by tpyl** [comment]
Unfortunately, I have very little time to work on this plugin and since I'm using Ubuntu 18.04  I'm not going to end up with Gnome 3.30 just yet. I'll surely fix this once Gnome 3.30 is pushed upon me. That said, There is a list of versions this has been tested on in metadata.json, and it caps out at 3.26.2. A simple thing  to try, which is probably not going to work, is to add 3.30 into this list...

**Comment by ProfRon** [comment]
Well, sooner or later Ubuntu will catch up with Archlinux (I guess).  No chance I can convert you to a rolling release model?    ;-)

Seriously now -- I tried adding 3.30 to metadata.json (should have thought have that myself) but it didn't help (as you suspected). 

Then I tried watching the output from journalctl while hitting ctl-alt-s, and found something relevant:

`    JS ERROR: TypeError: window.get_work_area_current_monitor is not a function
    snapToNeighbors@/home/ron/.local/share/gnome-shell/extension/gssnaptoneighbors@tpyl.github.io/extension.js:148:20
`

By the way, Looking Glass says that "gssnaptoneighbors.... has not emitted any errors".

**Comment by NinjaTurtle007** [comment]
I can also confirm it doesn't work on Gnome 3.30

To the dev, why you will be waiting to get gnome 3.30 to fix it when many people are using it?
I mean most people maintain their extensions even if they are not up with the latest version of whatever....

**Comment by tpyl** [comment]
It's open source, anyone is free to contribute. I encourage anyone capable who can easily test on Gnome 3.30 to submit a pull request.

**Comment by ProfRon** [comment]
Well, I've already _tested_ it, I even _diagnosed_ the problem (deprecated method, at least at first glance, see above), but for a pull request,   I'd have to have a _fix_, right? 

And Javascript is not one of my languages.  Yet. But who knows, perhaps I could fake it...
I'll see if I can get time and try to see if I can find a substitute for window.get_work_area_current_monitor.  

Any tips for where to search? Yes, "Google is my friend", but if I'm going to donate time, perhaps you could give me  a qualified pointer (or three?).

**Comment by tpyl** [comment]
I'm afraid I'm at a loss. The documentation for gnome extension development is basically non-existent and the extensions I studied to make this still seem to use that function... such as:

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/blob/master/extensions/screenshot-window-sizer/extension.js

**Comment by tpyl** [comment]
Actually, looking at that example again, it might be that the keybinding callback nolonger passes the "screen" parameter, so it's trying to access the function in the wrong object. The fix might be simply to change

function snapToNeighbors(display, screen, window, binding) {

to

function snapToNeighbors(display, window, binding) {

And this fix explains what's going on:

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/6583eae6225039b6b711918eff3a7cd0d03a42ca

**Comment by ProfRon** [comment]
I think we have a fix! I had to change two lines, but it just worked at least once. So no _real_ testing yet, but so far so good! Actually, it was three changes:
 1. I changed metadata.json to allow 3.30 (as discussed above)
 2. I changed line 139 of extension.js as per your suggestion, i.e. I simply removed the screen parameter to function snapToNeignbors
 3. It then crashed in line 49 (extension.js), but using the link you posted, I changed this line by replacing global.screen with global.workspaceManager, i.e.
```javascript
   -     let curWorkSpace = global.screen.get_active_workspace()
   +     let curWorkSpace = global.workspaceManager.get_active_workspace()
```
and it now seems to work!  
I'll let you know if I encounter other problems, but if you don't hear from me, then "no news is good news". 

Thanks,

Ron

P.S: I'd close this, but I'm not sure how you like issues to be handled, i.e. whether this needs to be committed first, or packaged as a pull request, or tested further... ?
